### ISSUE TITLE
Update Documentation on Downloading Icons

### ISSUE THREAD

**Issue by jsjoeio** [pacocoursey/Dusk#19]
Hi @pacocoursey ! 👋 

Currently, I'm not sure how I'm supposed to download multiple icons using the CLI tool. I thought I would put the icon names with spaces (see image below), but that doesn't seem to be right?

![screen shot 2018-11-26 at 11 08 38 am](https://user-images.githubusercontent.com/3806031/49033186-b5482900-f16b-11e8-89d0-5323d76c3667.png)

If you explain how, then I can add examples in the README 😄

**Comment by pacocoursey** [comment]
It's a comma separated list. Maybe space is a more natural separator? That's easy to change.

I added a small gif to the README demonstrating the CLI. Feel free to open a pull request adding more examples or documentation!

**Comment by jsjoeio** [comment]
No, I think your gif demonstrates it perfectly (plus your terminal looks beautiful 😍 btw)! Thanks for adding that :)
