### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by lndgalante** [pacocoursey/Dusk#2]
First of all, I really like these icons. Thank you for the work!

Will you be working with some of these: Firefox, Visual Studio Code, Franz, Framer?

Are you using it on your macOS? If you do can you share a screenshot?

**Comment by pacocoursey** [comment]
Completed Firefox #4, VSCode #5, Franz #7, Framer #6. Closing this as well :)

**Comment by lndgalante** [comment]
Already rocking it 🤘

Suggestion: Finder and Google Chrome since their take the full width and height of the circle kinda breaks the balance amongst the other icons?

<img width="1045" alt="captura de pantalla 2018-11-19 a la s 05 56 58" src="https://user-images.githubusercontent.com/2475912/48696256-2a41be80-ebc0-11e8-8429-a140e34ac4d7.png">

**Comment by lndgalante** [comment]
Been playing a little bit so I can came with an example 

<img width="1046" alt="captura de pantalla 2018-11-19 a la s 22 12 35" src="https://user-images.githubusercontent.com/2475912/48744994-6587d000-ec48-11e8-94cc-a4f73deef190.png">
