### ISSUE TITLE
CLI doesn't install all icons 

### ISSUE THREAD

**Issue by jsjoeio** [pacocoursey/Dusk#20]
![image](https://user-images.githubusercontent.com/3806031/49040271-4c6aac00-f17f-11e8-9632-4b6bd2f10983.png)

I used the CLI to install all icons but I'm not seeing any of the new ones (anki, teams, trello).

**Comment by pacocoursey** [comment]
Sorry, looks like I forgot to publish a new version.
`dusk-icons@0.1.0` should have all the new stuff :)
