### ISSUE TITLE
Icon Request: Sketch

### ISSUE THREAD

**Issue by b-b0t** [pacocoursey/Dusk#27]
https://www.sketchapp.com/

![sketch](https://user-images.githubusercontent.com/12721845/51072294-deaf0c80-1666-11e9-92e1-a75ba60118d5.png)

**Comment by b-b0t** [comment]
PS I'm thinking of contributing Office icons, what font is used on the Adobe icons?

**Comment by pacocoursey** [comment]
Hey, that would be great! I used [Gilroy Extra Bold](https://www.tinkov.info/gilroy.html), but maybe switching to a more common font would be better. Remaking the Adobe icons would only take a few minutes.

Sorry for the delay on creating the Sketch icon, just got back from vacation. Should be done soon.

**Comment by b-b0t** [comment]
No problems. I'm trying to get my dock entirely in these icons so will submit a pull request soon.

Might need help with the following:
Panic Transmit
Sequel Pro
Affinity Photo

 Would these be possible?

**Comment by pacocoursey** [comment]
The filled icon is practically impossible to do in only 2 colors, so I chose to go with an outlined version instead. Hope that works!

I have opened issues for Transmit, Sequel Pro, and Affinity Photo. I will complete those tomorrow.

**Comment by b-b0t** [comment]
The more minimal the better in my opinion. It looks great, thanks dude!

Will submit mine this weekend.
