### ISSUE TITLE
Icon Request: Sequel Pro

### ISSUE THREAD

**Issue by pacocoursey** [pacocoursey/Dusk#29]
# Sequel Pro

![Sequel Pro Icon](https://sequelpro.com/images/logo.png)

**Comment by b-b0t** [comment]
Sequel Pro update is in development and is using a newer version of the icon. It's also more minimal so should be easier. Even just a minimal database design would be cool.

![sequelpro](https://user-images.githubusercontent.com/12721845/51247385-9dd03400-1995-11e9-8dc9-a87249cf67f1.png)

**Comment by b-b0t** [comment]
Something like this:
![images](https://user-images.githubusercontent.com/12721845/51247465-e1c33900-1995-11e9-8bab-7d93f90288c3.png)
