### ISSUE TITLE
Thank you + Future Icons?

### ISSUE THREAD

**Issue by jsjoeio** [pacocoursey/Dusk#3]
Hi there! 

First, thanks for creating this! I had no idea you could customize your icons. 

Second, will there be future icons? Or is it possible for you to share a template that I can use to create my own and contribute to your project? I'd love to make some for the rest of my icons (i.e. Anki, Notion, iTerm, VSCode, Trello, Teams, Slack). 

I think I could make some in Figma, if you shared a template.

**Comment by pacocoursey** [comment]
Hey! Yes, there will be future icons, thanks for the suggestions.

There's no set template, just a `256px` radius circle and a central design element. I added some [contribution guidelines](https://github.com/pacocoursey/dusk/blob/master/CONTRIBUTING.md) to help clarify this.

I've been designing these in Illustrator and don't have any experience with Figma. If you come up with a template, I'd be happy to add it to the repo!

**Comment by jsjoeio** [comment]
Great, thank you for clarifying! And the contribution guideline is exactly what I was looking for. 

I'll see if I can create a template!

**Comment by lndgalante** [comment]
I don't know if @pacocoursey will agree but will be great if the template has some container so new icons don't break the balance between them for example: https://github.com/pacocoursey/Dusk/issues/2#issuecomment-439818463
And concept bringing that idea: https://github.com/pacocoursey/Dusk/issues/2#issuecomment-440100341

**Comment by jsjoeio** [comment]
@lndgalante I think I know what you're saying. 

Two templates:
1. the current one we have  
2. one for a smaller type of icon like you have in #2 

? 

If @pacocoursey agrees, and give me the dimensions @lndgalante , I'll be able to make additional templates!

**Comment by jsjoeio** [comment]
@pacocoursey Thanks for the update Paco. 

I'll go ahead and open issues for Anki and Teams. 

Closing this issue.
