### ISSUE TITLE
Icon Request: 1Password

### ISSUE THREAD

**Issue by b-b0t** [pacocoursey/Dusk#31]
Trying to commit an icon I created but have no access to contributing branch.

Please explain.

**Comment by pacocoursey** [comment]
The contributing branch was old and has been deleted.

As stated in the [contributing guidelines](https://github.com/pacocoursey/Dusk/blob/master/CONTRIBUTING.md), to submit a new icon you should

> open a pull request with the title `Add Icon: <app name>` after adding the .svg file to the svg/ folder, and listing the icon in the table at the bottom of the README.
